language:
  - python
  - node_js

python:
  - 2.7
node_js:
  - 0.10

install:
  # google app engine
  - curl -O https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip
  - unzip -q google_appengine_1.8.9.zip
  - mv google_appengine/google ./google
  # django
  - pip install -q Django==1.5 --use-mirrors
  # mock
  - pip install -U mock

before_script:
  - node -v
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm install -g grunt-cli

script:
  - python test.py
  - grunt test