application: django-kelp
version: 1
runtime: python27
api_version: 1
threadsafe: yes


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?tests/.*
- ^README.md
- ^\.gitignore
- ^\.gitmodules
- ^\.git/.*
- ^\.idea/.*
- ^_images/.*
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.sass
- ^(.*/)?.*\.rb


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: application.app


libraries:
- name: django
  version: "1.5"
